### ISSUE TITLE
Ошибка в коде: неверное использование curl_setopt() в классе Ulogin компанента ulogin:auth и классе ULoginSync компанента ulogin:sync

### ISSUE THREAD

**Issue by denisyfrolov** [ulogin/ulogin-Bitrix#1]
- **bitrix/components/ulogin/auth/include/Ulogin.class.php** строка **197**:

`curl_setopt($request, CURLOPT_FOLLOWLOCATION, 1);`
- **bitrix/components/ulogin/sync/include/UloginSync.class.php** строка **208**:

`curl_setopt($request, CURLOPT_FOLLOWLOCATION, 1);`

В обоих случаях попытка установить параметр сеанса CURL применяется к строковой переменной $request (строке с URL'ом сеанса), вместо переменной $c, хранящей сам сеанс. Что приводит к ошибкам:

> PHP Warning:  curl_setopt() expects parameter 1 to be resource, string given in .../bitrix/components/ulogin/auth/include/Ulogin.class.php on line 197
> 
> PHP Warning:  curl_setopt() expects parameter 1 to be resource, string given in .../bitrix/components/ulogin/sync/include/UloginSync.class.php on line 208

**Comment by ulogin-team** [comment]
Спасибо, что обратили наше внимание! 

Ошибку исправили. На самом деле, установка параметра CURLOPT_FOLLOWLOCATION вообще нежелательна, потому что на многих хостингах вызывает warning в логи, а пользы никакой. 
Просто удалили этот вызов. Заодно исправили протокол запроса на https. Давно пора.
